import { TrendingUp } from 'lucide-react'

interface SwapSectionProps {
  language: 'es' | 'en'
}

export default function SwapSection({ language }: SwapSectionProps) {


  const translations = {
    es: {
      title: 'Invierte en tu Futuro',
      subtitle: 'Compra $CAPITAL para asegurar tu jubilación',
      tokenTitle: '$CAPITAL Token',
      soon: 'Pronto',
      description1: 'podrás comprar $CAPITAL y, por lo tanto, tener derechos sobre una fracción de las ganancias generadas por el ecosistema de Pension Fi.',
      description2: 'Los holders de $CAPITAL podrán votar, contribuir y recibir ganancias del ecosistema.',
      comingSoon: 'Próximamente',
      investButton: 'Invertir (pronto)',
    },
    en: {
      title: 'Invest in Your Future',
      subtitle: 'Buy $CAPITAL to secure your retirement',
      tokenTitle: '$CAPITAL Token',
      soon: 'Soon',
      description1: 'you\'ll be able to buy $CAPITAL and hence have rights over a fraction of the profits generated by Pension Fi ecosystem.',
      description2: '$CAPITAL holders will be able to vote, contribute and receive profits from the ecosystem.',
      comingSoon: 'Coming Soon',
      investButton: 'Invest (soon)',
    },
  }
  const t = translations[language]

  return (
    <div className="flex-1 bg-white p-8 overflow-auto">
      <div className="max-w-3xl mx-auto">
        {/* Header */}
        <div className="text-center mb-12">
          <h1 className="text-4xl font-bold text-gray-900 mb-2">{t.title}</h1>
          <p className="text-gray-600">{t.subtitle}</p>
        </div>

        {/* Token Info Card */}
        <div className="bg-white border border-gray-200 rounded-lg p-8">
          <div className="flex items-center gap-2 mb-4">
            <TrendingUp className="h-5 w-5 text-gray-700" />
            <h2 className="text-xl font-semibold text-gray-900">{t.tokenTitle}</h2>
          </div>

          <div className="space-y-4 mb-6">
            <p className="text-gray-700">
              <span className="font-semibold">{t.soon}</span> {t.description1}
            </p>
            <p className="text-gray-700">
              {t.description2}
            </p>
          </div>

          {/* Coming Soon Badge */}
          <div className="text-center mb-6">
            <span className="inline-block text-[#27F5A9] text-xl font-semibold">
              {t.comingSoon}
            </span>
          </div>

          {/* Disabled Button */}
          <button
            disabled
            className="w-full bg-gray-900 text-white py-3 rounded-lg font-medium opacity-50 cursor-not-allowed"
          >
            {t.investButton}
          </button>
        </div>
      </div>
    </div>
  )
}
